import boto3
from botocore.config import Config
from boto_formatter.core_formatter import boto_response_formatter

"""
#boto_response_formatter(
service_name="apigateway",  **required
function_name="get_rest_apis", **required
format_type = "csv|json", optional default is json
 output_to="print|file|s3", optional default is none
 output_path="complete file path where you want to generate the output",optional
 prefix_columns="You can pass prefix columsn like regions/account": Optional
 pagination="If your result set is generated through Pagination it should have this attribute as yes": Optional
 required_only="if you want to print only important columns"
 )
"""


# Example : Pagination: If underlying function uses pagination you must pass pagination =True
@boto_response_formatter(
    service_name="ec2",
    function_name="describe_instances",
    format_type="csv",
    output_to="file",
    pagination="True",
)
def pagination_example():
    client = boto3.client("ec2")
    paginator = client.get_paginator("describe_instances")
    result = []
    for page in paginator.paginate():
        result.append(page)
    return result


# Example : Without Pagination: If underlying function not  uses pagination you don't pass pagination attribute
@boto_response_formatter(
    service_name="s3", function_name="list_buckets", format_type="csv", output_to="file"
)
def no_pagination_example():
    client = boto3.client("s3")
    result = client.list_buckets()
    return result


# Example : format_type can be json or csv
@boto_response_formatter(
    service_name="s3",
    function_name="list_buckets",
    format_type="json",
    output_to="file",
)
def json_format_example():
    client = boto3.client("s3")
    result = client.list_buckets()
    return result


# Example : You can use region when creating boto client to get list of resources in specfic region
@boto_response_formatter(
    service_name="ec2",
    function_name="describe_instances",
    format_type="csv",
    output_to="file",
    pagination="True",
)
def region_example():
    my_config = Config(region_name="us-west-2")
    client = boto3.client("ec2", config=my_config)
    paginator = client.get_paginator("describe_instances")
    result = []
    for page in paginator.paginate():
        result.append(page)
    return result


# Example :Passing response generated by boto_response_formatter decorator to another function
# Notice not passing file or any addtional attributes
@boto_response_formatter(service_name="s3", function_name="list_buckets")
def s3_bucket_flatten():
    client = boto3.client("s3")
    result = client.list_buckets()
    return result


# Example :Passing response generated by boto_response_formatter decorator to another function
def processing_example():
    response = s3_bucket_flatten()
    for bucket in response:
        print(bucket["Name"])
